# Generated by Django 3.0.14 on 2022-02-23 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20220223_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='register',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
