# Generated by Django 3.0.14 on 2022-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20220223_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
