# Generated by Django 3.0.14 on 2022-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_auto_20220223_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
