# Generated by Django 3.0.14 on 2022-02-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0006_auto_20220223_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('total_time_sec', models.IntegerField(blank=True, null=True)),
                ('speed', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='position.Property')),
            ],
            options={
                'ordering': ('-speed',),
            },
        ),
    ]
