# Generated by Django 3.0.14 on 2022-02-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0008_property_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
