# Generated by Django 3.0.14 on 2022-02-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0010_auto_20220224_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyDetail',
            new_name='PropertyInfo',
        ),
    ]
