# Generated by Django 3.0.14 on 2022-02-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0013_auto_20220224_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='propertyinfo',
            options={'ordering': ('-created',)},
        ),
    ]
